/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.mytwitter.telas;

import br.com.mytwitter.interfaces.IRepositorioUsuario;
import br.com.mytwitter.servicos.MyTwitter;
import br.com.mytwitter.servicos.Tweet;
import br.com.mytwitter.usuarios.Perfil;
import br.com.mytwitter.usuarios.PerfilDAO;
import br.com.mytwitter.usuarios.PessoaFisica;
import br.com.mytwitter.usuarios.PessoaJuridica;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author luisi
 */
public class TelaLogin extends javax.swing.JFrame {

    IRepositorioUsuario repositorio;

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
        //Instancia do repositorio
        repositorio = new PerfilDAO();
        MyTwitter twitter = new MyTwitter(repositorio);

        //Criação de um usuário
        Perfil p = new PessoaFisica("@luis");
        twitter.criarPerfil(p);

        //Criação de um usuário com erro
        Perfil p1 = new PessoaFisica("@luis");
        twitter.criarPerfil(p);
        System.out.println("Nome: " + p.getUsuario() + ", Status: " + String.valueOf(p.isStatus()));

        //Cancelamento de perfil e atualizar
        twitter.cancelarPerfil("@luis");
        Perfil p2 = repositorio.buscar("@luis");
        System.out.println("Nome: " + p.getUsuario() + ", Status: " + String.valueOf(p.isStatus()));

        //Cancelamento de perfil com erro
        twitter.cancelarPerfil("@luis");

        //Criação de mais usuários
        Perfil p3 = new PessoaJuridica("@rebeca");
        twitter.criarPerfil(p3);
        Perfil p4 = new PessoaFisica("@jesga");
        twitter.criarPerfil(p4);
        Perfil p5 = new PessoaJuridica("@mariana");
        twitter.criarPerfil(p5);

        //Seguir com erro de status
        twitter.seguir(p2.getUsuario(), p3.getUsuario());

        //Seguir com erro de nome
        twitter.seguir(p3.getUsuario(), "@lucas");

        //Seguir com erro de mesmo nome
        twitter.seguir(p3.getUsuario(), p3.getUsuario());

        //Estava assincrono?
        try {
            Thread.sleep(500);
        } catch (InterruptedException ex) {
            Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
        }

        //Seguir
        twitter.seguir(p3.getUsuario(), p4.getUsuario());
        twitter.seguir(p3.getUsuario(), p5.getUsuario());
        twitter.seguir(p4.getUsuario(), p5.getUsuario());

        //Lista de Seguidos
        Vector<Perfil> seguidos = new Vector<Perfil>();
        seguidos = twitter.seguidos("@rebeca");
        if (!seguidos.isEmpty()) {
            for (Perfil seguido : seguidos) {
                System.out.println("@rebeca segue " + seguido.getUsuario());
            }
        }

        //Lista seguidores
        Vector<Perfil> seguidores = new Vector<Perfil>();
        seguidores = twitter.seguidores("@mariana");
        if (!seguidores.isEmpty()) {
            for (Perfil seguidor : seguidores) {
                System.out.println("@mariana é seguida por " + seguidor.getUsuario());
            }
        }

        //Tweet
        twitter.tweetar(p5.getUsuario(), "Ques foi esse em?? #ufc #vidadificil #lulalivre");
        twitter.tweetar(p5.getUsuario(), "Pense numa cadeira massa essa de poo #poo #programacao #deusepai");
        twitter.tweetar(p5.getUsuario(), "Eu levo os refri repaziada #tbt #sextou #diademaldade");
        
        
        //Tweet excede numero
        twitter.tweetar(p5.getUsuario(), "Esse tweet vai execeder o numero de caracteres skdjfhbskjfbsjkhdbfakjshdbfkjahsdbfkjhasbdfkjhasbfkjhasbdkjfhabsdfjhsabljhsbflksjhbdlfksjdbflksajdbflaksjdbflaksdbflkabdlkjasbdkfjbskfgjbfkgjbdlkfhgbalkdfjgbdkljfbgkldjfbglkadjfbnglkjdfngldakjfngçafjngçakjfngakdjfngkladjnglakjfnglakfngljkadngkladngalknf #tbt #sextou #diademaldade");

        //Listando Tweets
        Vector<Tweet> tm = new Vector<Tweet>();
        tm = twitter.tweets("@mariana");
        if (!tm.isEmpty()) {
            for (Tweet tm1 : tm) {
                System.out.println("Nome: " + tm1.getUsuario() + " Tweet: " + tm1.getTweet());
            }
        }

        //Timeline de seguidor
        Vector<Tweet> tl = new Vector<Tweet>();
        tl = twitter.timeline("@jesga");
        if (!tl.isEmpty()) {
            for (Tweet tl1 : tl) {
                System.out.println("Timeline de @jesga - Nome: "+tl1.getUsuario()+" Tweet: "+tl1.getTweet());
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
